In [6]:
import yfinance as yf
import pandas as pd
import numpy as np

# Define the list of stock tickers
tickers = ['NVDA', 'SPY', 'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'BRK-B', 'JNJ', 'V']

# Download data for each stock
data = {}
for ticker in tickers:
    data[ticker] = yf.download(ticker, start='2018-01-01', end='2024-11-27', interval='1mo')['Adj Close']

# Download 1-month T-Bill (^IRX) data
rf = yf.download('^IRX', start='2018-01-01', end='2024-11-27', interval='1mo')['Adj Close'] / 100

# Align all data to the same index (the index of NVDA)
common_index = data['NVDA'].index

# Reindex all stocks and RF to match NVDA's index
for ticker in tickers:
    data[ticker] = data[ticker].reindex(common_index)
rf = rf.reindex(common_index)

# Forward-fill and backward-fill missing values in T-bill rate
rf.fillna(method='ffill', inplace=True)
rf.fillna(method='bfill', inplace=True)

# Create DataFrame with all aligned data
df_data = {'Date': common_index, '1M_TBill_Rate': rf.values.flatten()}
for ticker in tickers:
    df_data[f'{ticker}_Adj_Close'] = data[ticker].values.flatten()
    df_data[f'{ticker}_Log_Return'] = np.nan  # Leave an empty column for log returns

df = pd.DataFrame(df_data)

# Export the DataFrame to an Excel workbook
df.to_excel('stock_data.xlsx', index=False)

# Display the DataFrame
print(df)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

         Date  1M_TBill_Rate  NVDA_Adj_Close  NVDA_Log_Return  SPY_Adj_Close  \
0  2018-01-01        0.01430        6.078997              NaN     252.565262
1  2018-02-01        0.01618        5.985018              NaN     243.381851
2  2018-03-01        0.01670        5.731123              NaN     235.766373
3  2018-04-01        0.01763        5.565567              NaN     237.933945
4  2018-05-01        0.01870        6.240909              NaN     243.717926
..        ...            ...             ...              ...            ...
78 2024-07-01        0.05238      117.009987              NaN     549.125671
79 2024-08-01        0.05238      119.359795              NaN     561.956299
80 2024-09-01        0.05238      121.429619              NaN     572.005493
81 2024-10-01        0.05238      132.759995              NaN     568.640015
82 2024-11-01        0.05238      135.339996              NaN     598.830017

    SPY_Log_Return  AAPL_Adj_Close  AAPL_Log_Return  MSFT_Adj_Close  \
0              NaN       39.388077              NaN       88.027687
1              NaN       41.902908              NaN       86.878830
2              NaN       39.631340              NaN       84.959770
3              NaN       39.036095              NaN       87.054230
4              NaN       44.140598              NaN       92.006393
..             ...             ...              ...             ...
78             NaN      221.579468              NaN      416.763092
79             NaN      228.483871              NaN      415.557709
80             NaN      232.743942              NaN      429.440399
81             NaN      225.661728              NaN      405.538269
82             NaN      234.671814              NaN      422.145020

    MSFT_Log_Return  ...  META_Adj_Close  META_Log_Return  TSLA_Adj_Close  \
0               NaN  ...      186.328979              NaN       23.620667
1               NaN  ...      177.784729              NaN       22.870667
2               NaN  ...      159.310333              NaN       17.742001
3               NaN  ...      171.483688              NaN       19.593332
4               NaN  ...      191.204315              NaN       18.982000
..              ...  ...             ...              ...             ...
78              NaN  ...      474.377441              NaN      232.070007
79              NaN  ...      520.813171              NaN      214.110001
80              NaN  ...      571.894409              NaN      261.630005
81              NaN  ...      567.580017              NaN      249.850006
82              NaN  ...      569.200012              NaN      332.890015

    TSLA_Log_Return  BRK-B_Adj_Close  BRK-B_Log_Return  JNJ_Adj_Close  \
0               NaN       214.380005               NaN     113.904366
1               NaN       207.199997               NaN     107.054802
2               NaN       199.479996               NaN     106.305199
3               NaN       193.729996               NaN     104.928169
4               NaN       191.529999               NaN      99.229263
..              ...              ...               ...            ...
78              NaN       438.500000               NaN     155.413925
79              NaN       475.920013               NaN     163.300293
80              NaN       460.260010               NaN     160.770004
81              NaN       450.920013               NaN     158.587524
82              NaN       483.079987               NaN     154.163010

    JNJ_Log_Return  V_Adj_Close  V_Log_Return
0              NaN   118.365456           NaN
1              NaN   117.136368           NaN
2              NaN   114.171509           NaN
3              NaN   121.100807           NaN
4              NaN   124.765945           NaN
..             ...          ...           ...
78             NaN   264.635223           NaN
79             NaN   275.293518           NaN
80             NaN   274.428284           NaN
81             NaN   289.299988           NaN
82             NaN   314.102844           NaN

[83 rows x 24 columns]

C:\Users\kianh\AppData\Local\Temp\ipykernel_35676\1829111789.py:25: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rf.fillna(method='ffill', inplace=True)
C:\Users\kianh\AppData\Local\Temp\ipykernel_35676\1829111789.py:26: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rf.fillna(method='bfill', inplace=True)